//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.Callers = new HashSet<Caller>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int AddressID { get; set; }
        public string DoorNo { get; set; }
        public string BuildingName { get; set; }
        public string Street { get; set; }
        public string Address1 { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string LandMark { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual ICollection<Caller> Callers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
