//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUContactNumber
    {
        public int BUContactNumberID { get; set; }
        public int BusinessUnitID { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<bool> isSMSContact { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
    }
}
