//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnitCategory
    {
        public BusinessUnitCategory()
        {
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.BusinessUnitCategory1 = new HashSet<BusinessUnitCategory>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string LongName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual ICollection<BusinessUnitCategory> BusinessUnitCategory1 { get; set; }
        public virtual BusinessUnitCategory BusinessUnitCategory2 { get; set; }
    }
}
