//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnitType
    {
        public BusinessUnitType()
        {
            this.BusinessUnits = new HashSet<BusinessUnit>();
        }
    
        public int BusinessUnitTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SMSCountLimit { get; set; }
        public Nullable<int> SMSLimitFrequencyID { get; set; }
    
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual SMSLimitFrequency SMSLimitFrequency { get; set; }
    }
}
