//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV.DataProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dvradiusEntities : DbContext
    {
        public dvradiusEntities()
            : base("name=dvradiusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<BUContactNumber> BUContactNumbers { get; set; }
        public DbSet<BusinessUnit> BusinessUnits { get; set; }
        public DbSet<BusinessUnitCategory> BusinessUnitCategories { get; set; }
        public DbSet<BusinessUnitPhoneNumber> BusinessUnitPhoneNumbers { get; set; }
        public DbSet<BusinessUnitType> BusinessUnitTypes { get; set; }
        public DbSet<Caller> Callers { get; set; }
        public DbSet<CallerRequestHistory> CallerRequestHistories { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeType> EmployeeTypes { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<PhoneNumberType> PhoneNumberTypes { get; set; }
        public DbSet<Profession> Professions { get; set; }
        public DbSet<SMSHistory> SMSHistories { get; set; }
        public DbSet<SMSLimitFrequency> SMSLimitFrequencies { get; set; }
        public DbSet<SMSQueue> SMSQueues { get; set; }
        public DbSet<BusinessUnit_Flat> BusinessUnit_Flat { get; set; }
        public DbSet<vw_BusinessUnitPhoneNumbers> vw_BusinessUnitPhoneNumbers { get; set; }
    
        public virtual ObjectResult<GetBusinessUnits_Result> GetBusinessUnits(string searchstring, string area)
        {
            var searchstringParameter = searchstring != null ?
                new ObjectParameter("Searchstring", searchstring) :
                new ObjectParameter("Searchstring", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBusinessUnits_Result>("GetBusinessUnits", searchstringParameter, areaParameter);
        }
    
        public virtual ObjectResult<string> GetBusinessUnitsAutoPopulate(string searchstring)
        {
            var searchstringParameter = searchstring != null ?
                new ObjectParameter("Searchstring", searchstring) :
                new ObjectParameter("Searchstring", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetBusinessUnitsAutoPopulate", searchstringParameter);
        }
    
        public virtual int GetBusinessUnits_Old(string request)
        {
            var requestParameter = request != null ?
                new ObjectParameter("request", request) :
                new ObjectParameter("request", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetBusinessUnits_Old", requestParameter);
        }
    }
}
