//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DV.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSQueue
    {
        public int SMSQueueID { get; set; }
        public string RecipientMobileNumber { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> QueueDateTime { get; set; }
        public Nullable<int> ReturnCode { get; set; }
        public string ReturnMessage { get; set; }
        public Nullable<bool> isSMSSent { get; set; }
        public Nullable<System.DateTime> ProcessedDateTime { get; set; }
        public Nullable<bool> isProcessed { get; set; }
    }
}
